#!/usr/bin/env python3
import os, sys

_srcdir = '%s' % os.path.dirname(os.path.realpath(__file__))
_filepath = os.path.dirname(sys.argv[0])
sys.path.insert(1, os.path.join(_filepath, _srcdir))

if sys.version_info[0] == 3:
    from bydict import __main__

    #这里是个相对包导入地址,holly shit!!! very disgusting!!!
    if __name__ == '__main__':
        __main__.main()
        
else: # Python 2
    print("Python3 needed!")
